### ISSUE TITLE
Flesh out tests

### ISSUE THREAD

**Issue by Drewsmits** [danieltiger/Pilot#21]
We need to make sure our coverage is a lot better, and that we have helpful NSAsserts sprinkled around

**Comment by Drewsmits** [comment]
I spent some time getting ready to test the entire suite, and realized quickly that we can't push nav controllers in a test environment.  We would have to implement KIF, or something like that, to get that testing to work.  The test apps are probably more than sufficient to work for this.  What do you think , @danieltiger?

**Comment by danieltiger** [comment]
I think the test apps are fine, we're covering all the cases.
